"""Prompt construction for the LLM batch cache generator.

Three public functions:

* ``build_system_prompt()``    — static system instructions + few-shot
                                  examples (called once, result cached).
* ``build_user_prompt()``      — per-day user turn with ticker features.
* ``build_correction_prompt()``— follow-up turn after a parse failure.

Few-shot examples
-----------------
Two concrete input→output demonstrations are appended to the system
prompt.  They are generated by calling ``build_user_prompt()`` on fixed
example records, so the input sections are *always* byte-for-byte
identical to what the real pipeline produces — any format change
automatically propagates to the examples.

The example output strings are hardcoded JSON that passes
``parse_response()`` validation.  They cover two key failure modes that
models tend to mis-handle:

  Example 1 (2 tickers) — veto=true with required reason + confidence.
    Reinforces: raw JSON only, veto fields must all be set together.

  Example 2 (3 tickers) — weak-signal veto, regime < 1.0, correct ranks.
    Reinforces: all tickers present, unique ranks, regime below neutral.
"""
from __future__ import annotations

import functools
from typing import Any


# ── System prompt (base) ──────────────────────────────────────────────────

_SYSTEM_PROMPT_BASE = """\
You are an expert quantitative analyst specialising in Korean equity momentum \
strategies.

Your task: given a batch of candidate stock features for a single trading day, \
produce structured JSON trading signals consumed by an automated backtest engine.

━━━ FEATURE GLOSSARY ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

base_score
    Raw momentum selection score (typically 1.0–5.0). Higher = stronger candidate.

momentum_quality_score  [0–1]
    Quality of recent short-term price momentum.
    ≥ 0.50 = healthy momentum    < 0.20 = weak or absent

trend_quality_score  [0–1]
    Alignment of price action with the medium-term trend.
    ≥ 0.50 = trend-aligned       < 0.20 = counter-trend or ranging

range_recovery_bonus  [0–1]
    Intraday recovery off the session low (demand signal).
    ≥ 0.30 = strong intraday demand

overheat_penalty  [0–1]
    Overbought / extension risk — price has run too far too fast.
    > 0.25 = extended; candidate at risk of mean-reversion

pullback_exhaustion_penalty  [0–1]
    Stalled pullback with no follow-through buying — momentum fading.
    > 0.20 = exhausted; upside limited

decision          Engine pre-filter verdict: "approved" or "rejected"
rule_gate_passed  All rule-based filters cleared (bool)
score_gate_passed Scored above entry threshold (bool)

━━━ OUTPUT FORMAT ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Respond with a single raw JSON object — no markdown fences, no prose before or \
after:

{
  "regime_multiplier": <float, 0.80–1.20>,
  "tickers": {
    "<TICKER>": {
      "delta":           <float, -5.0 to +5.0>,
      "veto":            <bool>,
      "veto_confidence": <float, 0.0–1.0>,
      "veto_reason":     <null | "overheat" | "pullback_exhaustion" | "weak_signal" | "regime_risk" | "other">,
      "rank":            <int, unique, 1 = highest quality>
    }
  }
}

━━━ SIGNAL SEMANTICS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

regime_multiplier
    Market-wide quality this session.
    0.80 = poor conditions, reduce position sizing
    1.00 = neutral
    1.20 = excellent conditions, full sizing

delta  [-5, +5]
    Additive adjustment to the engine's selection score.
    Positive values increase the chance this ticker is selected today.
    Negative values suppress it.  Zero = no opinion.

veto  [bool]
    True blocks the ticker from selection regardless of engine score.
    Use sparingly — only when you have high confidence in a near-term loss.

veto_confidence  [0–1]
    Confidence in the veto.  Required > 0.0 when veto = true.
    When veto = false, use to signal residual concern (0.0 = none).

veto_reason
    Categorical cause when veto = true; null otherwise.

rank  [1 .. N]
    Relative ranking of candidates for today. 1 = strongest, N = weakest.
    Ranks must be unique integers; gaps will be renormalised automatically.

━━━ RULES ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

1. Include EVERY ticker from the input — no omissions.
2. Ranks must be unique integers starting from 1.
3. When veto = true you MUST set veto_confidence > 0.0 AND a non-null veto_reason.
4. Respond with raw JSON only.  No code fences.  No commentary.
"""


# ── Few-shot example data ─────────────────────────────────────────────────
#
# Records are defined as plain dicts so `build_user_prompt()` can render
# them — input sections are always exactly consistent with the live format.
#
# Tickers use real KRX codes; feature values are realistic and the
# expected outputs are logically consistent with the feature semantics.

# Example 1 — 2024-01-15, 2 tickers
# 005930 (Samsung Electronics): strong momentum, healthy trend → rank 1, positive delta, no veto
# 000660 (SK Hynix): low momentum, severe overheat → rank 2, vetoed for overheat
_EX1_DATE = "2024-01-15"
_EX1_RECORDS: list[dict[str, Any]] = [
    {
        "date": _EX1_DATE,
        "ticker": "005930",
        "base_score": 3.2,
        "features": {
            "momentum_quality_score": 0.68,
            "trend_quality_score": 0.72,
            "range_recovery_bonus": 0.35,
            "overheat_penalty": 0.04,
            "pullback_exhaustion_penalty": 0.02,
        },
        "decision": "approved",
        "rule_gate_passed": True,
        "score_gate_passed": True,
    },
    {
        "date": _EX1_DATE,
        "ticker": "000660",
        "base_score": 1.9,
        "features": {
            "momentum_quality_score": 0.22,
            "trend_quality_score": 0.15,
            "range_recovery_bonus": 0.08,
            "overheat_penalty": 0.44,
            "pullback_exhaustion_penalty": 0.06,
        },
        "decision": "approved",
        "rule_gate_passed": True,
        "score_gate_passed": True,
    },
]
# Tickers the parser must find in Example 1's output.
EX1_TICKERS: list[str] = ["005930", "000660"]

# Hardcoded expected output for Example 1.
# Deliberately uses one-ticker-per-line JSON so the structure is readable
# inside the system prompt.  The parser accepts any valid JSON layout.
_EX1_OUTPUT = """{
  "regime_multiplier": 1.05,
  "tickers": {
    "005930": {"delta": 2.10, "veto": false, "veto_confidence": 0.05, "veto_reason": null, "rank": 1},
    "000660": {"delta": -1.90, "veto": true, "veto_confidence": 0.82, "veto_reason": "overheat", "rank": 2}
  }
}"""

# Example 2 — 2024-01-22, 3 tickers
# 006400 (Samsung SDI): strong across all dimensions → rank 1
# 035420 (NAVER): moderate quality, no concerns → rank 2
# 051910 (LG Chem): base_score < 1 AND momentum < 0.10 → weak_signal veto, rank 3
# Regime below neutral (mixed quality day)
_EX2_DATE = "2024-01-22"
_EX2_RECORDS: list[dict[str, Any]] = [
    {
        "date": _EX2_DATE,
        "ticker": "006400",
        "base_score": 3.8,
        "features": {
            "momentum_quality_score": 0.62,
            "trend_quality_score": 0.58,
            "range_recovery_bonus": 0.40,
            "overheat_penalty": 0.05,
            "pullback_exhaustion_penalty": 0.03,
        },
        "decision": "approved",
        "rule_gate_passed": True,
        "score_gate_passed": True,
    },
    {
        "date": _EX2_DATE,
        "ticker": "035420",
        "base_score": 2.5,
        "features": {
            "momentum_quality_score": 0.45,
            "trend_quality_score": 0.38,
            "range_recovery_bonus": 0.22,
            "overheat_penalty": 0.06,
            "pullback_exhaustion_penalty": 0.08,
        },
        "decision": "approved",
        "rule_gate_passed": True,
        "score_gate_passed": True,
    },
    {
        "date": _EX2_DATE,
        "ticker": "051910",
        "base_score": 0.8,
        "features": {
            "momentum_quality_score": 0.07,
            "trend_quality_score": 0.10,
            "range_recovery_bonus": 0.03,
            "overheat_penalty": 0.02,
            "pullback_exhaustion_penalty": 0.12,
        },
        "decision": "approved",
        "rule_gate_passed": True,
        "score_gate_passed": True,
    },
]
EX2_TICKERS: list[str] = ["006400", "035420", "051910"]

_EX2_OUTPUT = """{
  "regime_multiplier": 0.91,
  "tickers": {
    "006400": {"delta": 1.60, "veto": false, "veto_confidence": 0.06, "veto_reason": null, "rank": 1},
    "035420": {"delta": 0.30, "veto": false, "veto_confidence": 0.18, "veto_reason": null, "rank": 2},
    "051910": {"delta": -2.50, "veto": true, "veto_confidence": 0.76, "veto_reason": "weak_signal", "rank": 3}
  }
}"""


# ── Few-shot block builder ────────────────────────────────────────────────


def _build_few_shot_block() -> str:
    """Build the few-shot section by rendering example records through
    ``build_user_prompt()``.

    Called lazily so the input sections are always identical to what the
    real pipeline sends to the LLM — any spacing or field-order change in
    ``build_user_prompt()`` automatically propagates here.
    """
    ex1_input = build_user_prompt(_EX1_DATE, _EX1_RECORDS)
    ex2_input = build_user_prompt(_EX2_DATE, _EX2_RECORDS)
    return (
        "\n"
        "━━━ EXAMPLES ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "\n"
        "Study the two examples below before responding.\n"
        "Each shows the exact input format followed by the expected raw JSON output.\n"
        "\n"
        "── Example 1 of 2  (2 tickers — one vetoed for overheat) ───────────────\n"
        "Input:\n"
        f"{ex1_input}\n"
        "\n"
        "Output:\n"
        f"{_EX1_OUTPUT}\n"
        "\n"
        "── Example 2 of 2  (3 tickers — weak-signal veto, regime < 1.0) ────────\n"
        "Input:\n"
        f"{ex2_input}\n"
        "\n"
        "Output:\n"
        f"{_EX2_OUTPUT}\n"
        "\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "Now respond to the next user message using the same format.\n"
    )


# ── Public API ────────────────────────────────────────────────────────────


@functools.lru_cache(maxsize=1)
def build_system_prompt() -> str:
    """Return the full system prompt: base instructions + few-shot examples.

    Result is cached after the first call — the function is pure and the
    examples are deterministic, so caching is safe.
    """
    return _SYSTEM_PROMPT_BASE + _build_few_shot_block()


# ── User prompt (per day) ─────────────────────────────────────────────────

# Feature keys we always show first, in this order.
_PRIORITY_FEATURE_KEYS: tuple[str, ...] = (
    "momentum_quality_score",
    "trend_quality_score",
    "range_recovery_bonus",
    "overheat_penalty",
    "pullback_exhaustion_penalty",
)


def build_user_prompt(
    date_key: str,
    day_records: list[dict[str, Any]],
) -> str:
    """Build the user-turn prompt for a single trading day.

    Parameters
    ----------
    date_key:
        ISO date string, e.g. ``"2024-01-15"``.
    day_records:
        List of JSONL records (all sharing ``date_key``).  Each record has
        at minimum ``ticker``, ``base_score``, ``features``, ``decision``,
        ``rule_gate_passed``, ``score_gate_passed``.
    """
    lines: list[str] = [
        f"Date: {date_key}",
        f"Candidates: {len(day_records)}",
        "",
    ]

    for rec in day_records:
        ticker = rec.get("ticker", "?")
        base = rec.get("base_score", 0.0)
        features: dict[str, Any] = rec.get("features") or {}
        decision = rec.get("decision", "unknown")
        rule_gate = rec.get("rule_gate_passed")
        score_gate = rec.get("score_gate_passed")

        lines.append(f"Ticker: {ticker}")
        lines.append(f"  base_score            {_fmt_float(base)}")
        lines.append(f"  decision              {decision}")
        lines.append(f"  rule_gate_passed      {rule_gate}")
        lines.append(f"  score_gate_passed     {score_gate}")

        # Priority features first, then any extras.
        emitted: set[str] = set()
        for key in _PRIORITY_FEATURE_KEYS:
            if key in features:
                lines.append(f"  {key:<30}  {_fmt_float(features[key])}")
                emitted.add(key)
        for key, val in features.items():
            if key not in emitted:
                try:
                    lines.append(f"  {key:<30}  {_fmt_float(val)}")
                except (TypeError, ValueError):
                    lines.append(f"  {key:<30}  {val!r}")

        lines.append("")

    tickers_csv = ", ".join(
        str(r.get("ticker", "?")) for r in day_records
    )
    lines.append(
        f"Provide signals for all {len(day_records)} ticker(s): {tickers_csv}"
    )
    return "\n".join(lines)


def _fmt_float(v: Any) -> str:
    try:
        return f"{float(v):.4f}"
    except (TypeError, ValueError):
        return str(v)


# ── Correction prompt ─────────────────────────────────────────────────────


def build_correction_prompt(error_description: str) -> str:
    """Build the follow-up user turn after a parse failure.

    Parameters
    ----------
    error_description:
        Human-readable description of what went wrong with the previous
        response (from ``ParseError``).
    """
    return (
        f"Your previous response could not be parsed.\n"
        f"Error: {error_description}\n\n"
        "Please provide a corrected response that is valid JSON matching the "
        "required schema exactly.\n"
        "— No markdown code fences.\n"
        "— No prose before or after the JSON.\n"
        "— Every ticker from the original request must be present.\n"
        "— Ranks must be unique integers starting from 1."
    )
